#ifndef __KL2EDK_AUTOGEN_aliases__
#define __KL2EDK_AUTOGEN_aliases__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'aliases.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

namespace Fabric { namespace EDK { namespace KL {


// KL alias 'HRESULT'
// Defined at R:\src\HordeSoftware\Fabric2Arnold\GenKL/\_opaque_types.kl:10:1
typedef UInt32 HRESULT;
}}}

#endif // __KL2EDK_AUTOGEN_aliases__
