#ifndef __KL2EDK_AUTOGEN_aliases__
#define __KL2EDK_AUTOGEN_aliases__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'aliases.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

namespace Fabric { namespace EDK { namespace KL {

}}}

#endif // __KL2EDK_AUTOGEN_aliases__
