#ifndef __KL2EDK_AUTOGEN_ARGB__
#define __KL2EDK_AUTOGEN_ARGB__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'ARGB.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'ARGB'

struct ARGB
{
  typedef ARGB &Result;
  typedef ARGB const &INParam;
  typedef ARGB &IOParam;
  
  UInt8 a;
  UInt8 r;
  UInt8 g;
  UInt8 b;
};

inline void Traits<ARGB>::ConstructEmpty( ARGB &val )
{
  Traits< UInt8 >::ConstructEmpty( val.a );
  Traits< UInt8 >::ConstructEmpty( val.r );
  Traits< UInt8 >::ConstructEmpty( val.g );
  Traits< UInt8 >::ConstructEmpty( val.b );
}
inline void Traits<ARGB>::ConstructCopy( ARGB &lhs, ARGB const &rhs )
{
  Traits< UInt8 >::ConstructCopy( lhs.a, rhs.a );
  Traits< UInt8 >::ConstructCopy( lhs.r, rhs.r );
  Traits< UInt8 >::ConstructCopy( lhs.g, rhs.g );
  Traits< UInt8 >::ConstructCopy( lhs.b, rhs.b );
}
inline void Traits<ARGB>::AssignCopy( ARGB &lhs, ARGB const &rhs )
{
  Traits< UInt8 >::AssignCopy( lhs.a, rhs.a );
  Traits< UInt8 >::AssignCopy( lhs.r, rhs.r );
  Traits< UInt8 >::AssignCopy( lhs.g, rhs.g );
  Traits< UInt8 >::AssignCopy( lhs.b, rhs.b );
}
inline void Traits<ARGB>::Destruct( ARGB &val )
{
  Traits< UInt8 >::Destruct( val.b );
  Traits< UInt8 >::Destruct( val.g );
  Traits< UInt8 >::Destruct( val.r );
  Traits< UInt8 >::Destruct( val.a );
}
}}}

#endif // __KL2EDK_AUTOGEN_ARGB__
