#ifndef __KL2EDK_AUTOGEN_AtAOVSampleIterator__
#define __KL2EDK_AUTOGEN_AtAOVSampleIterator__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtAOVSampleIterator.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtAOVSampleIterator'

struct AtAOVSampleIterator
{
  typedef AtAOVSampleIterator &Result;
  typedef AtAOVSampleIterator const &INParam;
  typedef AtAOVSampleIterator &IOParam;
  
  Data _handle;
};

inline void Traits<AtAOVSampleIterator>::ConstructEmpty( AtAOVSampleIterator &val )
{
  Traits< Data >::ConstructEmpty( val._handle );
}
inline void Traits<AtAOVSampleIterator>::ConstructCopy( AtAOVSampleIterator &lhs, AtAOVSampleIterator const &rhs )
{
  Traits< Data >::ConstructCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtAOVSampleIterator>::AssignCopy( AtAOVSampleIterator &lhs, AtAOVSampleIterator const &rhs )
{
  Traits< Data >::AssignCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtAOVSampleIterator>::Destruct( AtAOVSampleIterator &val )
{
  Traits< Data >::Destruct( val._handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtAOVSampleIterator__
