#ifndef __KL2EDK_AUTOGEN_AtNodeEntry__
#define __KL2EDK_AUTOGEN_AtNodeEntry__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtNodeEntry.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtNodeEntry'
// Defined at R:\src\HordeSoftware\demoarnoldapp\fabric2arnold\GenKL/\_opaque_types.kl:26:1

struct AtNodeEntry
{
  typedef AtNodeEntry &Result;
  typedef AtNodeEntry const &INParam;
  typedef AtNodeEntry &IOParam;
  typedef AtNodeEntry &OUTParam;
  
  Data _handle;
};

inline void Traits<AtNodeEntry>::ConstructEmpty( AtNodeEntry &val )
{
  Traits< Data >::ConstructEmpty( val._handle );
}
inline void Traits<AtNodeEntry>::ConstructCopy( AtNodeEntry &lhs, AtNodeEntry const &rhs )
{
  Traits< Data >::ConstructCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtNodeEntry>::AssignCopy( AtNodeEntry &lhs, AtNodeEntry const &rhs )
{
  Traits< Data >::AssignCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtNodeEntry>::Destruct( AtNodeEntry &val )
{
  Traits< Data >::Destruct( val._handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtNodeEntry__
