#ifndef __KL2EDK_AUTOGEN_AtRGBA__
#define __KL2EDK_AUTOGEN_AtRGBA__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtRGBA.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"


#endif // __KL2EDK_AUTOGEN_AtRGBA__
