#ifndef __KL2EDK_AUTOGEN_AtUserParamEntry__
#define __KL2EDK_AUTOGEN_AtUserParamEntry__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'AtUserParamEntry.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'AtUserParamEntry'
// Defined at GenKL//_opaque_types.kl:86:1

struct AtUserParamEntry
{
  typedef AtUserParamEntry &Result;
  typedef AtUserParamEntry const &INParam;
  typedef AtUserParamEntry &IOParam;
  
  Data _handle;
};

inline void Traits<AtUserParamEntry>::ConstructEmpty( AtUserParamEntry &val )
{
  Traits< Data >::ConstructEmpty( val._handle );
}
inline void Traits<AtUserParamEntry>::ConstructCopy( AtUserParamEntry &lhs, AtUserParamEntry const &rhs )
{
  Traits< Data >::ConstructCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtUserParamEntry>::AssignCopy( AtUserParamEntry &lhs, AtUserParamEntry const &rhs )
{
  Traits< Data >::AssignCopy( lhs._handle, rhs._handle );
}
inline void Traits<AtUserParamEntry>::Destruct( AtUserParamEntry &val )
{
  Traits< Data >::Destruct( val._handle );
}
}}}

#endif // __KL2EDK_AUTOGEN_AtUserParamEntry__
