#ifndef __KL2EDK_AUTOGEN_Euler_d__
#define __KL2EDK_AUTOGEN_Euler_d__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Euler_d.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "RotationOrder.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Euler_d'
// Defined at Euler_d.kl:22:1

struct Euler_d
{
  typedef Euler_d &Result;
  typedef Euler_d const &INParam;
  typedef Euler_d &IOParam;
  typedef Euler_d &OUTParam;
  
  Float64 x;
  Float64 y;
  Float64 z;
  RotationOrder ro;
};

inline void Traits<Euler_d>::ConstructEmpty( Euler_d &val )
{
  Traits< Float64 >::ConstructEmpty( val.x );
  Traits< Float64 >::ConstructEmpty( val.y );
  Traits< Float64 >::ConstructEmpty( val.z );
  Traits< RotationOrder >::ConstructEmpty( val.ro );
}
inline void Traits<Euler_d>::ConstructCopy( Euler_d &lhs, Euler_d const &rhs )
{
  Traits< Float64 >::ConstructCopy( lhs.x, rhs.x );
  Traits< Float64 >::ConstructCopy( lhs.y, rhs.y );
  Traits< Float64 >::ConstructCopy( lhs.z, rhs.z );
  Traits< RotationOrder >::ConstructCopy( lhs.ro, rhs.ro );
}
inline void Traits<Euler_d>::AssignCopy( Euler_d &lhs, Euler_d const &rhs )
{
  Traits< Float64 >::AssignCopy( lhs.x, rhs.x );
  Traits< Float64 >::AssignCopy( lhs.y, rhs.y );
  Traits< Float64 >::AssignCopy( lhs.z, rhs.z );
  Traits< RotationOrder >::AssignCopy( lhs.ro, rhs.ro );
}
inline void Traits<Euler_d>::Destruct( Euler_d &val )
{
  Traits< RotationOrder >::Destruct( val.ro );
  Traits< Float64 >::Destruct( val.z );
  Traits< Float64 >::Destruct( val.y );
  Traits< Float64 >::Destruct( val.x );
}
}}}

#endif // __KL2EDK_AUTOGEN_Euler_d__
