#ifndef __KL2EDK_AUTOGEN_Fabric2Arnold__
#define __KL2EDK_AUTOGEN_Fabric2Arnold__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Fabric2Arnold.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha2
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

#include "ARGB.h"
#include "AtAOVEntry.h"
#include "AtAOVIterator.h"
#include "AtArray.h"
#include "AtBucket.h"
#include "AtCameraInput.h"
#include "AtCameraOutput.h"
#include "AtLicenseInfo.h"
#include "AtList.h"
#include "AtMetaDataEntry.h"
#include "AtMetaDataIterator.h"
#include "AtMetaDataStore.h"
#include "AtNode.h"
#include "AtNodeEntry.h"
#include "AtNodeEntryIterator.h"
#include "AtNodeIterator.h"
#include "AtNodeLib.h"
#include "AtNodeMethods.h"
#include "AtParamEntry.h"
#include "AtParamIterator.h"
#include "AtParamValue.h"
#include "AtParamValue_functions.h"
#include "AtRay.h"
#include "AtScrSample.h"
#include "AtShaderGlobals.h"
#include "AtTextureHandle.h"
#include "AtTextureParams.h"
#include "AtUserParamEntry.h"
#include "AtUserParamIterator.h"
#include "Box2.h"
#include "Box3.h"
#include "Color.h"
#include "Euler.h"
#include "Euler_d.h"
#include "Euler_i.h"
#include "Mat22.h"
#include "Mat22_d.h"
#include "Mat22_i.h"
#include "Mat33.h"
#include "Mat33_d.h"
#include "Mat33_i.h"
#include "Mat44.h"
#include "Mat44_d.h"
#include "Mat44_i.h"
#include "Quat.h"
#include "Quat_d.h"
#include "Quat_i.h"
#include "RGB.h"
#include "RGBA.h"
#include "Ray.h"
#include "RotationOrder.h"
#include "Vec2.h"
#include "Vec2_d.h"
#include "Vec2_i.h"
#include "Vec3.h"
#include "Vec3_d.h"
#include "Vec3_i.h"
#include "Vec4.h"
#include "Vec4_d.h"
#include "Vec4_i.h"
#include "Xfo.h"
#include "global_functions.h"

#endif // __KL2EDK_AUTOGEN_Fabric2Arnold__
