#ifndef __KL2EDK_AUTOGEN_Mat44__
#define __KL2EDK_AUTOGEN_Mat44__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Mat44.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 2.1.0-alpha3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 2 || FABRIC_EDK_VERSION_MIN != 1
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Vec4.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Mat44'

struct Mat44
{
  typedef Mat44 &Result;
  typedef Mat44 const &INParam;
  typedef Mat44 &IOParam;
  typedef Mat44 &OUTParam;
  
  Vec4 row0;
  Vec4 row1;
  Vec4 row2;
  Vec4 row3;
};

inline void Traits<Mat44>::ConstructEmpty( Mat44 &val )
{
  Traits< Vec4 >::ConstructEmpty( val.row0 );
  Traits< Vec4 >::ConstructEmpty( val.row1 );
  Traits< Vec4 >::ConstructEmpty( val.row2 );
  Traits< Vec4 >::ConstructEmpty( val.row3 );
}
inline void Traits<Mat44>::ConstructCopy( Mat44 &lhs, Mat44 const &rhs )
{
  Traits< Vec4 >::ConstructCopy( lhs.row0, rhs.row0 );
  Traits< Vec4 >::ConstructCopy( lhs.row1, rhs.row1 );
  Traits< Vec4 >::ConstructCopy( lhs.row2, rhs.row2 );
  Traits< Vec4 >::ConstructCopy( lhs.row3, rhs.row3 );
}
inline void Traits<Mat44>::AssignCopy( Mat44 &lhs, Mat44 const &rhs )
{
  Traits< Vec4 >::AssignCopy( lhs.row0, rhs.row0 );
  Traits< Vec4 >::AssignCopy( lhs.row1, rhs.row1 );
  Traits< Vec4 >::AssignCopy( lhs.row2, rhs.row2 );
  Traits< Vec4 >::AssignCopy( lhs.row3, rhs.row3 );
}
inline void Traits<Mat44>::Destruct( Mat44 &val )
{
  Traits< Vec4 >::Destruct( val.row3 );
  Traits< Vec4 >::Destruct( val.row2 );
  Traits< Vec4 >::Destruct( val.row1 );
  Traits< Vec4 >::Destruct( val.row0 );
}
}}}

#endif // __KL2EDK_AUTOGEN_Mat44__
