#ifndef __KL2EDK_AUTOGEN_Quat__
#define __KL2EDK_AUTOGEN_Quat__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'Quat.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"
#include "Vec3.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'Quat'

struct Quat
{
  typedef Quat &Result;
  typedef Quat const &INParam;
  typedef Quat &IOParam;
  
  Vec3 v;
  Float32 w;
};

inline void Traits<Quat>::ConstructEmpty( Quat &val )
{
  Traits< Vec3 >::ConstructEmpty( val.v );
  Traits< Float32 >::ConstructEmpty( val.w );
}
inline void Traits<Quat>::ConstructCopy( Quat &lhs, Quat const &rhs )
{
  Traits< Vec3 >::ConstructCopy( lhs.v, rhs.v );
  Traits< Float32 >::ConstructCopy( lhs.w, rhs.w );
}
inline void Traits<Quat>::AssignCopy( Quat &lhs, Quat const &rhs )
{
  Traits< Vec3 >::AssignCopy( lhs.v, rhs.v );
  Traits< Float32 >::AssignCopy( lhs.w, rhs.w );
}
inline void Traits<Quat>::Destruct( Quat &val )
{
  Traits< Float32 >::Destruct( val.w );
  Traits< Vec3 >::Destruct( val.v );
}
}}}

#endif // __KL2EDK_AUTOGEN_Quat__
