#ifndef __KL2EDK_AUTOGEN_RGBA__
#define __KL2EDK_AUTOGEN_RGBA__

#ifdef KL2EDK_INCLUDE_MESSAGES
  #pragma message ( "Including 'RGBA.h'" )
#endif

////////////////////////////////////////////////////////////////
// THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT MODIFY!!
////////////////////////////////////////////////////////////////
// Generated by kl2edk version 1.15.3
////////////////////////////////////////////////////////////////

#include <FabricEDK.h>
#if FABRIC_EDK_VERSION_MAJ != 1 || FABRIC_EDK_VERSION_MIN != 15
# error "This file needs to be rebuilt for the current EDK version!"
#endif

#include "global.h"

namespace Fabric { namespace EDK { namespace KL {

// KL struct 'RGBA'

struct RGBA
{
  typedef RGBA &Result;
  typedef RGBA const &INParam;
  typedef RGBA &IOParam;
  
  UInt8 r;
  UInt8 g;
  UInt8 b;
  UInt8 a;
};

inline void Traits<RGBA>::ConstructEmpty( RGBA &val )
{
  Traits< UInt8 >::ConstructEmpty( val.r );
  Traits< UInt8 >::ConstructEmpty( val.g );
  Traits< UInt8 >::ConstructEmpty( val.b );
  Traits< UInt8 >::ConstructEmpty( val.a );
}
inline void Traits<RGBA>::ConstructCopy( RGBA &lhs, RGBA const &rhs )
{
  Traits< UInt8 >::ConstructCopy( lhs.r, rhs.r );
  Traits< UInt8 >::ConstructCopy( lhs.g, rhs.g );
  Traits< UInt8 >::ConstructCopy( lhs.b, rhs.b );
  Traits< UInt8 >::ConstructCopy( lhs.a, rhs.a );
}
inline void Traits<RGBA>::AssignCopy( RGBA &lhs, RGBA const &rhs )
{
  Traits< UInt8 >::AssignCopy( lhs.r, rhs.r );
  Traits< UInt8 >::AssignCopy( lhs.g, rhs.g );
  Traits< UInt8 >::AssignCopy( lhs.b, rhs.b );
  Traits< UInt8 >::AssignCopy( lhs.a, rhs.a );
}
inline void Traits<RGBA>::Destruct( RGBA &val )
{
  Traits< UInt8 >::Destruct( val.a );
  Traits< UInt8 >::Destruct( val.b );
  Traits< UInt8 >::Destruct( val.g );
  Traits< UInt8 >::Destruct( val.r );
}
}}}

#endif // __KL2EDK_AUTOGEN_RGBA__
